"""Update Booking model

Revision ID: 3ad1f96f2202
Revises: 7680ce2e7fd2
Create Date: 2026-07-11 00:23:52.008219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad1f96f2202'
down_revision = '7680ce2e7fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('booking_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salon_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salon_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'salons', ['salon_id'], ['id'])
        batch_op.alter_column('booking_time',
               existing_type=sa.String(length=20),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
